export const products = [
  {
    brand: 'Sony',
    title: 'Camera Canon EOS 2000D Kit EF-S18-55mm',
    price: '$9.122',
    oldPrice: '$1.350',
    reviews: 50,
    discount: 'On Sale -10%',
    isNew: true,
  },
  {
    brand: 'Sony',
    title: 'Smart Watch Sony SW750',
    price: '$9.122',
    oldPrice: '$1.350',
    reviews: 25,
    discount: 'On Sale -10%',
    isNew: true,
  },
  {
    brand: 'Sony',
    title: 'Smart Watch Sony SW750',
    price: '$9.122',
    oldPrice: '$1.350',
    reviews: 25,
    discount: 'On Sale -10%',
    isNew: true,
  },
  {
    brand: 'Sony',
    title: 'Smart Watch Sony SW750',
    price: '$9.122',
    oldPrice: '$1.350',
    reviews: 25,
    discount: 'On Sale -10%',
    isNew: true,
  },
  {
    brand: 'Sony',
    title: 'Smart Watch Sony SW750',
    price: '$9.122',
    oldPrice: '$1.350',
    reviews: 25,
    discount: 'On Sale -10%',
    isNew: true,
  },
];
